openapi: 3.0.3
info:
  title: View Self Assessment Account
  description: |-
    This API provides a breakdown of Self Assessment liability, showing overdue, payable and pending amounts, within HMRC tax account services.

      | Version | Date       | Author   | Description                        |
      |---------|------------|----------|------------------------------------|
      | 0.1.0   | 24-06-2025 | Ali Kouhestani | Initial draft                |
      | 0.2.0   | 25-06-2025 | Ali Kouhestani | Changed description to accurately reflect the one used on the service guide|

  x-integration-catalogue:
    reviewed-date: 2025-07-24T09:00:00.000000000Z
    short-description: Self Assessment liability details
  version: 0.2.0
servers:
  - url: https://test-api.service.hmrc.gov.uk
    description: Sandbox
  - url: https://api.service.hmrc.gov.uk
    description: Production
security:
  - oAuth2:
      - User Restricted
      - read:self-assessment
paths:
  /accounts/breakdown/self-assessment/{utr}:
    get:
      tags:
        - Self Assessment Account Details
      summary: Account Details
      description: |
        <b>Examples</b><br>
        /accounts/breakdown/self-assessment/12345678/?fromDate=24-08-2024
      parameters:
        - in: header
          name: Authorization
          description: |
            An OAuth 2.0 Bearer Token with the *read:self-assessment* scope.
          required: true
          schema:
            type: string
            example: "Bearer bb7fed3fe10dd235a2ccda3d50fb"
        - in: query
          name: fromDate
          required: false
          schema:
            $ref: "#/components/schemas/dateType"
        - $ref: '#/components/parameters/utr'
      responses:
        '200':
          description: Successful
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/successResponse'
              examples:
                example 1:
                  $ref: '#/components/examples/successResponseExample'
        '400':
          description: Bad request
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/responseType'
              examples:
                error400ResponseBodyExample:
                  $ref: '#/components/examples/error400ResponseBodyExample'
        "401":
          description: Unauthorised
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/responseType'
              examples:
                error401ResponseBodyExample:
                  $ref: '#/components/examples/error401ResponseBodyExample'
        "403":
          description: Forbidden
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/responseType'
              examples:
                error403ResponseBodyExample:
                  $ref: '#/components/examples/error403ResponseBodyExample'
        '404':
          description: Not found
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/responseType'
              examples:
                error404ResponseBodyExample:
                  $ref: '#/components/examples/error404ResponseBodyExample'
        '500':
          description: Internal Server Error
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/responseType'
              examples:
                error500ResponseBodyExample:
                  $ref: '#/components/examples/error500ResponseBodyExample'
        '503':
          description: Service unavailable
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/responseType'
              examples:
                error503ResponseBodyExample:
                  $ref: '#/components/examples/error503ResponseBodyExample'

components:
  securitySchemes:
    oAuth2:
      type: oauth2
      description: HMRC supports OAuth 2.0 for authenticating user restricted API requests using an OAuth 2.0 Bearer Token in the AUTHORIZATION header.
        Please see the [developer hub](https://developer.service.hmrc.gov.uk/api-documentation/docs/authorisation/user-restricted-endpoints) for more details.
      flows:
        authorizationCode:
          authorizationUrl: https://api.service.hmrc.gov.uk/oauth/authorize
          tokenUrl: https://api.service.hmrc.gov.uk/oauth/token
          refreshUrl: https://api.service.hmrc.gov.uk/oauth/refresh
          scopes:
            "read:self-assessment": Read self-assessment data
  headers:
    Authorization:
      description: An OAuth 2.0 Bearer Token with the *read:self-assessment* scope.
      schema:
        type: string
        example: Bearer bb7fed3fe10dd235a2ccda3d50fb
  parameters:
    fromDate:
      in: query
      name: fromDate
      required: true
      schema:
        $ref: "#/components/schemas/dateType"
    utr:
      in: path
      name: utr
      required: true
      schema:
        type: string
        pattern: ^\d{10}$
  schemas:
    amountType_11_2:
      description: "Currency amount. 13-digits total with 2 decimal places"
      type: "number"
      minimum: -9.999999999999E10
      maximum: 9.999999999999E10
      multipleOf: 0.01
    dateType:
      type: string
      pattern: ^(((19|20)([2468][048]|[13579][26]|0[48])|2000)[-]02[-]29|((19|20)[0-9]{2}[-](0[469]|11)[-](0[1-9]|1[0-9]|2[0-9]|30)|(19|20)[0-9]{2}[-](0[13578]|1[02])[-](0[1-9]|[12][0-9]|3[01])|(19|20)[0-9]{2}[-]02[-](0[1-9]|1[0-9]|2[0-8])))$
    responseType:
      required:
        - failure
      type: object
      properties:
        failure:
          type: object
          required:
            - type
            - reason
          properties:
            type:
              type: string
            reason:
              type: string
          additionalProperties: false
    successResponse:
      type: object
      required:
        - balanceDetails
      properties:
        balanceDetails:
          type: object
          properties:
            totalOverdueBalance:
              $ref: "#/components/schemas/amountType_11_2"
            totalPayableBalance:
              $ref: "#/components/schemas/amountType_11_2"
            payableDueDate:
              $ref: "#/components/schemas/dateType"
            totalPendingBalance:
              $ref: "#/components/schemas/amountType_11_2"
            pendingDueDate:
              $ref: "#/components/schemas/dateType"
            totalBalance:
              $ref: "#/components/schemas/amountType_11_2"
            totalCodedOut:
              $ref: "#/components/schemas/amountType_11_2"
            totalCreditAvailable:
              $ref: "#/components/schemas/amountType_11_2"
          additionalProperties: false
          required:
            - totalOverdueBalance
            - totalPayableBalance
            - totalPendingBalance
            - totalBalance
            - totalCodedOut
            - totalCreditAvailable
        chargeDetails:
          type: array
          items:
            required:
              - chargeAmount
              - chargeId
              - chargeType
              - creationDate
              - dueDate
              - outstandingAmount
              - taxYear
            type: object
            properties:
              accruingInterest:
                $ref: "#/components/schemas/amountType_11_2"
              accruingInterestDateRange:
                type: object
                properties:
                  interestStartDate:
                    $ref: "#/components/schemas/dateType"
                  interestEndDate:
                    $ref: "#/components/schemas/dateType"
              accruingInterestRate:
                $ref: "#/components/schemas/amountType_11_2"
              amendments:
                type: array
                items:
                  required:
                    - amendmentAmount
                    - amendmentDate
                    - amendmentReason
                  type: object
                  properties:
                    amendmentDate:
                      $ref: "#/components/schemas/dateType"
                    amendmentAmount:
                      $ref: "#/components/schemas/amountType_11_2"
                    amendmentReason:
                      type: string
                      minLength: 1
                      maxLength: 100
                    newChargeBalance:
                      $ref: "#/components/schemas/amountType_11_2"
                    paymentMethod:
                      type: string
                      minLength: 1
                      maxLength: 30
                    paymentDate:
                      $ref: "#/components/schemas/dateType"
                  additionalProperties: false
              chargeId:
                type: string
                pattern: ^[0-9]{1,12}$
              chargeType:
                type: string
                minLength: 1
                maxLength: 30
              chargeAmount:
                $ref: "#/components/schemas/amountType_11_2"
              codedOutDetail:
                type: array
                items:
                  type: object
                  properties:
                    amount:
                      $ref: "#/components/schemas/amountType_11_2"
                    effectiveDate:
                      $ref: "#/components/schemas/dateType"
                    effectiveTaxYear:
                      $ref: "#/components/schemas/yearType"
                    taxYear:
                      $ref: "#/components/schemas/yearType"
                  additionalProperties: false
              creationDate:
                $ref: "#/components/schemas/dateType"
              dueDate:
                $ref: "#/components/schemas/dateType"
              interestAmountDue:
                $ref: "#/components/schemas/amountType_11_2"
              outstandingAmount:
                $ref: "#/components/schemas/amountType_11_2"
              taxYear:
                $ref: "#/components/schemas/yearType"
            additionalProperties: false
        refundDetails:
          type: array
          items:
            type: object
            required:
              - issueDate
              - refundActualAmount
              - refundRequestAmount
            properties:
              issueDate:
                $ref: "#/components/schemas/dateType"
              interestAddedToRefund:
                $ref: "#/components/schemas/amountType_11_2"
              refundActualAmount:
                $ref: "#/components/schemas/amountType_11_2"
              refundMethod:
                type: string
                pattern: ^[a-zA-Z ]{1,30}$
              refundReference:
                type: string
                pattern: ^[a-zA-Z0-9]{1,12}$
              refundRequestAmount:
                $ref: "#/components/schemas/amountType_11_2"
              refundRequestDate:
                $ref: "#/components/schemas/dateType"
              refundStatus:
                type: string
                pattern: ^[a-zA-Z ]{1,32}$
            additionalProperties: false
        paymentHistoryDetails:
          type: array
          items:
            type: object
            required:
              - paymentAmount
              - paymentDate
              - paymentId
            properties:
              allocationReference:
                type: string
                minLength: 1
                maxLength: 35
              dateProcessed:
                $ref: "#/components/schemas/dateType"
              paymentAmount:
                $ref: "#/components/schemas/amountType_11_2"
              paymentMethod:
                type: string
                minLength: 1
                maxLength: 30
              paymentId:
                type: string
                minLength: 1
                maxLength: 35
              paymentDate:
                $ref: "#/components/schemas/dateType"
            additionalProperties: false
      additionalProperties: false
    yearType:
      type: string
      pattern: ^([0-9]{4})$
  examples:
    error400ResponseBodyExample:
      value:
        failure:
          type: BAD_REQUEST
          reason: Invalid request format or parameters.
    error401ResponseBodyExample:
      value:
        failure:
          type: UNAUTHORISED
          reason: Authorisation failed.
    error403ResponseBodyExample:
      value:
        failure:
          type: FORBIDDEN
          reason: Access not permitted.
    error404ResponseBodyExample:
      value:
        failure:
          type: NOT_FOUND
          reason: No data found for the UTR provided.
    error500ResponseBodyExample:
      value:
        failure:
          type: INTERNAL_SERVER_ERROR
          reason: Unexpected internal error. Please contact service desk.
    error503ResponseBodyExample:
      value:
        failure:
          type: SERVICE_UNAVAILABLE
          reason: Service unavailable. Please try again later.
    successResponseExample:
      value:
        balanceDetails:
          totalOverdueBalance: 500
          totalPayableBalance: 500
          payableDueDate: 2025-04-31
          totalPendingBalance: 1500
          pendingDueDate: '2025-07-15'
          totalBalance: 2000
          totalCodedOut: 250
          totalCreditAvailable: 0
        chargeDetails:
          - chargeId: AB1234567
            creationDate: '2025-01-15'
            chargeType: ITSA
            chargeAmount: 1250
            outstandingAmount: 500
            taxYear: 2024-2025
            dueDate: 2025-04-31
            amendments:
              amendmentDate: '2025-04-15'
              amendmentAmount: 500
              newChargeBalance: 750
              paymentMethod: bank_transfer
              paymentDate: '2025-04-10'
            codedOutDetail:
              - amount: 250
                effectiveDate: '2025-04-01'
                taxYear: 2024
                effectiveTaxYear: 2025
          - chargeId: EF2345678
            creationDate: '2024-02-10'
            chargeType: NICS
            chargeAmount: 2200
            outstandingAmount: 0
            taxYear: 2023
            dueDate: '2024-04-01'
            interestAmountDue: "20.00"
            accruingInterestDateRange:
              interestStartDate: '2024-05-01'
              interestEndDate: '2024-12-01'
            interestRate: 0.05
            amendments:
              newChargeBalance: 2000
              amendmentDate: '2024-12-08'
              amendmentAmount: 2058.33
              paymentMethod: bank_transfer
              paymentDate: '2024-12-03'
          - chargeId: KL3456789
            creationDate: '2025-05-22'
            chargeType: VATC
            chargeAmount: 1500
            outstandingAmount: 1500
            taxYear: 2025
            dueDate: '2025-07-15'
        refundDetails:
          - issueDate: '2024-01-10'
            refundMethod: bank_transfer
            refundRequestDate: '2023-12-12'
            refundRequestAmount: 350
            refundDescription: 'From overpayment from return 05 APR 23'
            interestAddedToRefund: 5.25
            refundActualAmount: 355.25
            refundStatus: processed
        paymentHistoryDetails:
          - paymentAmount: 500
            paymentId: PAY123456
            paymentMethod: bank_transfer
            paymentDate: '2025-04-11'
            dateProcessed: '2025-04-15'
            allocationReference: AB1234567
          - paymentAmount: 2058.33
            paymentId: PAY112233
            paymentMethod: bank_transfer
            paymentDate: '2024-12-04'
            dateProcessed: '2024-12-08'
            allocationReference: EF2345678
          - paymentAmount: 200
            paymentId: PAY888233
            paymentMethod: bank_transfer
            paymentDate: '2023-12-04'
            dateProcessed: '2023-12-08'
            allocationReference: EF2345678